---
- name: restarting the service of httpd
  hosts: node1,node2
  tasks:
   - name: Install httpd
     yum:
      name: httpd
      state: present
   - name: tweak the motd file
     copy:
      content: |
       Hey Httpd requires a restart
      dest: /etc/motd
     notify:
      - restart httpd
  handlers:
    - name: restart httpd
      service:
       name: httpd
       state: started
