---
- name: Ansible - GIT - Jenkins 
  hosts: node1
  tasks:
   - name: Say HELLO world
     command: echo "Hi Successfully Integrated Ansible-GIT-Jenkins"
     register: output
   - debug:
      var: output
