---
- name: Ansible - GIT - Jenkins 
  hosts: node1
  tasks:
   - name: Say HELLO world
     command: echo "Successfully Ansible-GIT-Jenkins integration is done"
     register: output
   - debug:
      var: output
