---
- name: local variable call
  hosts: all
  vars:
   - package: wget
   - package1: ntp
  tasks:
   - name: Install package wget
     yum:
      name: "{{ package }}"
      state: present
   - name: Install package ntp
     yum:
      name: "{{package1}}"
      state: present
